In [1]:
# Importing the necessary packages

import tensorflow as tf
import numpy as np
from collections import Counter
import random

In [2]:
sentence_pairs = [
    ("அவன் புத்தகம் வேலை செய்கிறேன்", "he is working a book"),
    ("அவன் பந்தை பாடுகிறேன்", "he is singing a ball"),
    ("நான் திட்டம் விளையாடுகிறேன்", "i am playing a plan"),
    ("நான் திட்டம் சமைக்கிறேன்", "i am cooking a plan"),
    ("நீ திட்டம் பாடுகிறேன்", "you are singing a plan"),
    ("நான் புத்தகம் பாடுகிறேன்", "i am singing a book"),
    ("அவன் பந்தை சமைக்கிறேன்", "he is cooking a ball"),
    ("நீ பாடல் சமைக்கிறேன்", "you are cooking a song"),
    ("நீ பந்தை பாடுகிறேன்", "you are singing a ball"),
    ("நீ உணவு பாடுகிறேன்", "you are singing food"),
    ("நாங்கள் திட்டம் சமைக்கிறேன்", "we are cooking a plan"),
    ("நாங்கள் பந்தை வேலை செய்கிறேன்", "we are working a ball"),
    ("நாங்கள் திட்டம் பாடுகிறேன்", "we are singing a plan"),
    ("நான் பாடல் சமைக்கிறேன்", "i am cooking a song"),
    ("அவன் திட்டம் விளையாடுகிறேன்", "he is playing a plan"),
    ("நீ பந்தை சமைக்கிறேன்", "you are cooking a ball"),
    ("அவன் பந்தை விளையாடுகிறேன்", "he is playing a ball"),
    ("அவள் புத்தகம் விளையாடுகிறேன்", "she is playing a book"),
    ("அவள் உணவு விளையாடுகிறேன்", "she is playing food"),
    ("அவர்கள் புத்தகம் சமைக்கிறேன்", "they are cooking a book"),
    ("அவள் உணவு படிக்கிறேன்", "she is reading food"),
    ("அவள் திட்டம் விளையாடுகிறேன்", "she is playing a plan"),
    ("நான் பாடல் பாடுகிறேன்", "i am singing a song"),
    ("நீ உணவு வேலை செய்கிறேன்", "you are working food"),
    ("நாங்கள் திட்டம் விளையாடுகிறேன்", "we are playing a plan"),
    ("நான் உணவு படிக்கிறேன்", "i am reading food"),
    ("அவள் திட்டம் சமைக்கிறேன்", "she is cooking a plan"),
    ("நாங்கள் பாடல் படிக்கிறேன்", "we are reading a song"),
    ("அவர்கள் பந்தை சமைக்கிறேன்", "they are cooking a ball"),
    ("அவன் உணவு படிக்கிறேன்", "he is reading food"),
    ("நான் புத்தகம் படிக்கிறேன்", "i am reading a book"),
    ("அவன் பந்தை படிக்கிறேன்", "he is reading a ball"),
    ("அவன் உணவு பாடுகிறேன்", "he is singing food"),
    ("அவள் பந்தை வேலை செய்கிறேன்", "she is working a ball"),
    ("அவள் பந்தை பாடுகிறேன்", "she is singing a ball"),
    ("நீ திட்டம் சமைக்கிறேன்", "you are cooking a plan"),
    ("அவள் புத்தகம் சமைக்கிறேன்", "she is cooking a book"),
    ("நாங்கள் புத்தகம் பாடுகிறேன்", "we are singing a book"),
    ("அவர்கள் திட்டம் படிக்கிறேன்", "they are reading a plan"),
    ("அவள் புத்தகம் வேலை செய்கிறேன்", "she is working a book"),
    ("அவள் உணவு பாடுகிறேன்", "she is singing food"),
    ("அவள் பாடல் பாடுகிறேன்", "she is singing a song"),
    ("அவன் திட்டம் பாடுகிறேன்", "he is singing a plan"),
    ("நான் திட்டம் படிக்கிறேன்", "i am reading a plan"),
    ("நான் திட்டம் பாடுகிறேன்", "i am singing a plan"),
    ("நீ பாடல் வேலை செய்கிறேன்", "you are working a song"),
    ("அவள் பந்தை விளையாடுகிறேன்", "she is playing a ball"),
    ("அவள் திட்டம் வேலை செய்கிறேன்", "she is working a plan"),
    ("நாங்கள் பந்தை பாடுகிறேன்", "we are singing a ball"),
    ("அவர்கள் திட்டம் பாடுகிறேன்", "they are singing a plan"),
    ("அவன் புத்தகம் சமைக்கிறேன்", "he is cooking a book"),
    ("அவன் திட்டம் சமைக்கிறேன்", "he is cooking a plan"),
    ("நான் உணவு பாடுகிறேன்", "i am singing food"),
    ("நான் பந்தை வேலை செய்கிறேன்", "i am working a ball"),
    ("நாங்கள் புத்தகம் வேலை செய்கிறேன்", "we are working a book"),
    ("அவர்கள் திட்டம் வேலை செய்கிறேன்", "they are working a plan"),
    ("நாங்கள் பந்தை சமைக்கிறேன்", "we are cooking a ball"),
    ("நீ புத்தகம் சமைக்கிறேன்", "you are cooking a book"),
    ("அவள் உணவு வேலை செய்கிறேன்", "she is working food"),
    ("அவன் உணவு சமைக்கிறேன்", "he is cooking food"),
    ("நாங்கள் பாடல் பாடுகிறேன்", "we are singing a song"),
    ("நாங்கள் உணவு வேலை செய்கிறேன்", "we are working food"),
    ("அவன் பாடல் வேலை செய்கிறேன்", "he is working a song"),
    ("அவர்கள் திட்டம் சமைக்கிறேன்", "they are cooking a plan"),
    ("அவர்கள் பாடல் விளையாடுகிறேன்", "they are playing a song"),
    ("அவர்கள் புத்தகம் பாடுகிறேன்", "they are singing a book"),
    ("அவன் புத்தகம் படிக்கிறேன்", "he is reading a book"),
    ("அவன் பாடல் சமைக்கிறேன்", "he is cooking a song"),
    ("அவன் திட்டம் படிக்கிறேன்", "he is reading a plan"),
    ("நாங்கள் புத்தகம் விளையாடுகிறேன்", "we are playing a book"),
    ("அவன் உணவு விளையாடுகிறேன்", "he is playing food"),
    ("நாங்கள் உணவு சமைக்கிறேன்", "we are cooking food"),
    ("நாங்கள் பாடல் சமைக்கிறேன்", "we are cooking a song"),
    ("அவர்கள் திட்டம் விளையாடுகிறேன்", "they are playing a plan"),
    ("அவள் உணவு சமைக்கிறேன்", "she is cooking food"),
    ("அவர்கள் பந்தை படிக்கிறேன்", "they are reading a ball"),
    ("நீ பந்தை படிக்கிறேன்", "you are reading a ball"),
    ("அவன் திட்டம் வேலை செய்கிறேன்", "he is working a plan"),
    ("அவன் பாடல் பாடுகிறேன்", "he is singing a song"),
    ("நான் திட்டம் வேலை செய்கிறேன்", "i am working a plan"),
    ("நாங்கள் திட்டம் வேலை செய்கிறேன்", "we are working a plan"),
    ("அவன் உணவு வேலை செய்கிறேன்", "he is working food"),
    ("அவர்கள் உணவு விளையாடுகிறேன்", "they are playing food"),
    ("அவள் திட்டம் படிக்கிறேன்", "she is reading a plan"),
    ("நீ திட்டம் விளையாடுகிறேன்", "you are playing a plan"),
    ("அவர்கள் புத்தகம் விளையாடுகிறேன்", "they are playing a book"),
    ("அவள் பந்தை படிக்கிறேன்", "she is reading a ball"),
    ("அவர்கள் பாடல் பாடுகிறேன்", "they are singing a song"),
    ("நீ பாடல் பாடுகிறேன்", "you are singing a song"),
    ("அவள் பாடல் சமைக்கிறேன்", "she is cooking a song"),
    ("அவன் பாடல் படிக்கிறேன்", "he is reading a song"),
    ("அவர்கள் உணவு படிக்கிறேன்", "they are reading food"),
    ("நீ உணவு படிக்கிறேன்", "you are reading food"),
    ("நான் புத்தகம் விளையாடுகிறேன்", "i am playing a book"),
    ("நீ புத்தகம் படிக்கிறேன்", "you are reading a book"),
    ("அவள் புத்தகம் பாடுகிறேன்", "she is singing a book"),
    ("அவர்கள் புத்தகம் வேலை செய்கிறேன்", "they are working a book"),
    ("அவன் பாடல் விளையாடுகிறேன்", "he is playing a song"),
    ("நீ உணவு சமைக்கிறேன்", "you are cooking food"),
    ("நான் பாடல் வேலை செய்கிறேன்", "i am working a song"),
    ("நாங்கள் பாடல் வேலை செய்கிறேன்", "we are working a song"),
    ("நான் பந்தை சமைக்கிறேன்", "i am cooking a ball"),
    ("அவள் பாடல் விளையாடுகிறேன்", "she is playing a song"),
    ("அவள் பாடல் வேலை செய்கிறேன்", "she is working a song"),
    ("அவர்கள் பந்தை வேலை செய்கிறேன்", "they are working a ball"),
    ("அவர்கள் உணவு பாடுகிறேன்", "they are singing food"),
    ("நாங்கள் பாடல் விளையாடுகிறேன்", "we are playing a song"),
    ("நாங்கள் உணவு படிக்கிறேன்", "we are reading food"),
    ("அவள் பந்தை சமைக்கிறேன்", "she is cooking a ball"),
    ("நான் புத்தகம் சமைக்கிறேன்", "i am cooking a book"),
    ("அவள் புத்தகம் படிக்கிறேன்", "she is reading a book"),
    ("அவர்கள் உணவு சமைக்கிறேன்", "they are cooking food"),
    ("நான் உணவு சமைக்கிறேன்", "i am cooking food"),
    ("நான் பந்தை பாடுகிறேன்", "i am singing a ball"),
    ("நாங்கள் உணவு விளையாடுகிறேன்", "we are playing food"),
    ("நீ பந்தை விளையாடுகிறேன்", "you are playing a ball"),
    ("அவன் புத்தகம் விளையாடுகிறேன்", "he is playing a book"),
    ("நான் பாடல் விளையாடுகிறேன்", "i am playing a song"),
    ("அவர்கள் உணவு வேலை செய்கிறேன்", "they are working food"),
    ("அவர்கள் பந்தை விளையாடுகிறேன்", "they are playing a ball"),
    ("நீ புத்தகம் விளையாடுகிறேன்", "you are playing a book"),
    ("அவன் புத்தகம் பாடுகிறேன்", "he is singing a book"),
    ("நீ பந்தை வேலை செய்கிறேன்", "you are working a ball"),
    ("நாங்கள் புத்தகம் சமைக்கிறேன்", "we are cooking a book"),
    ("அவள் பாடல் படிக்கிறேன்", "she is reading a song"),
    ("நாங்கள் திட்டம் படிக்கிறேன்", "we are reading a plan"),
    ("நான் பாடல் படிக்கிறேன்", "i am reading a song"),
    ("நீ பாடல் விளையாடுகிறேன்", "you are playing a song"),
    ("அவர்கள் பாடல் படிக்கிறேன்", "they are reading a song"),
    ("நான் உணவு வேலை செய்கிறேன்", "i am working food"),
    ("நான் உணவு விளையாடுகிறேன்", "i am playing food"),
    ("அவர்கள் பாடல் சமைக்கிறேன்", "they are cooking a song"),
    ("அவர்கள் புத்தகம் படிக்கிறேன்", "they are reading a book"),
    ("நீ புத்தகம் வேலை செய்கிறேன்", "you are working a book"),
    ("அவர்கள் பந்தை பாடுகிறேன்", "they are singing a ball"),
    ("அவன் பந்தை வேலை செய்கிறேன்", "he is working a ball"),
    ("அவர்கள் பாடல் வேலை செய்கிறேன்", "they are working a song"),
    ("நாங்கள் பந்தை படிக்கிறேன்", "we are reading a ball"),
    ("நீ உணவு விளையாடுகிறேன்", "you are playing food"),
    ("நான் பந்தை படிக்கிறேன்", "i am reading a ball"),
    ("நாங்கள் புத்தகம் படிக்கிறேன்", "we are reading a book"),
    ("நாங்கள் பந்தை விளையாடுகிறேன்", "we are playing a ball"),
    ("அவள் திட்டம் பாடுகிறேன்", "she is singing a plan"),
    ("நான் புத்தகம் வேலை செய்கிறேன்", "i am working a book"),
    ("நீ பாடல் படிக்கிறேன்", "you are reading a song"),
    ("நீ புத்தகம் பாடுகிறேன்", "you are singing a book"),
    ("நான் பந்தை விளையாடுகிறேன்", "i am playing a ball"),
    ("நாங்கள் உணவு பாடுகிறேன்", "we are singing food"),
    ("நீ திட்டம் வேலை செய்கிறேன்", "you are working a plan"),
    ("நீ திட்டம் படிக்கிறேன்", "you are reading a plan"),
]

In [3]:
# Function to build the vocabulary

def build_vocab(data):
    tokens =  Counter()
    for sent in data:
        tokens.update(sent.split())
    vocab = {"<PAD>": 0, "<SOS>": 1, "<EOS>": 2}
    for i, token in enumerate(tokens.keys(), 3):
        vocab[token] = i
    return vocab

In [4]:
# Splitting the tamil and english sentence

tam_sent = [pair[0] for pair in sentence_pairs]
eng_sent = [pair[1].lower() for pair in sentence_pairs]


In [5]:
# Building the vocobulary for the both languages
tam_vocab = build_vocab(tam_sent)
eng_vocab = build_vocab(eng_sent)

In [6]:
print(f'Tamil vocobulary is {tam_vocab}')
print(f'English vocobulary is {eng_vocab}')


Tamil vocobulary is {'<PAD>': 0, '<SOS>': 1, '<EOS>': 2, 'அவன்': 3, 'புத்தகம்': 4, 'வேலை': 5, 'செய்கிறேன்': 6, 'பந்தை': 7, 'பாடுகிறேன்': 8, 'நான்': 9, 'திட்டம்': 10, 'விளையாடுகிறேன்': 11, 'சமைக்கிறேன்': 12, 'நீ': 13, 'பாடல்': 14, 'உணவு': 15, 'நாங்கள்': 16, 'அவள்': 17, 'அவர்கள்': 18, 'படிக்கிறேன்': 19}
English vocobulary is {'<PAD>': 0, '<SOS>': 1, '<EOS>': 2, 'he': 3, 'is': 4, 'working': 5, 'a': 6, 'book': 7, 'singing': 8, 'ball': 9, 'i': 10, 'am': 11, 'playing': 12, 'plan': 13, 'cooking': 14, 'you': 15, 'are': 16, 'song': 17, 'food': 18, 'we': 19, 'she': 20, 'they': 21, 'reading': 22}


In [7]:
# Sentence to indices 

def sent2indices(data, vocab):
    indices = [vocab.get(i.lower(), vocab.get('<UNK>', 0)) for i in data.split()]
    data_indices = [vocab['<SOS>']] + indices + [vocab['<EOS>']]
    return data_indices


In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Preprocessing the text, converting the text into sequences with padding
def pre_processing(sequence_data, src_vocab, targ_vocab):
    src_data = [sent2indices(data[1].lower(), src_vocab) for data in sequence_data]
    tar_data = [sent2indices(data[0], targ_vocab) for data in sequence_data]

    # padding to the dataset

    src_seq = pad_sequences(src_data, padding='post', value= src_vocab['<PAD>'])
    tar_seq = pad_sequences(tar_data, padding='post', value= targ_vocab['<PAD>'])

    return(src_seq, tar_seq)


In [9]:
eng_seq, tam_seq = pre_processing(sentence_pairs, eng_vocab, tam_vocab)

In [10]:
print(f'English Sequence: \n {eng_seq}')

English Sequence: 
 [[ 1  3  4 ...  6  7  2]
 [ 1  3  4 ...  6  9  2]
 [ 1 10 11 ...  6 13  2]
 ...
 [ 1 19 16 ... 18  2  0]
 [ 1 15 16 ...  6 13  2]
 [ 1 15 16 ...  6 13  2]]


In [11]:
# Creating an encoder
from tensorflow.keras.layers import Embedding, LSTM, Dense

class Encoder(tf.keras.Model):
    def __init__(self, input_size, embed_size, hidden_size):
        super(Encoder, self).__init__()

        self.embedding = Embedding(input_size, embed_size)
        self.lstm = LSTM(hidden_size, return_state=True)

    def call(self, data):
        embed = self.embedding(data)
        _, hidden, cell = self.lstm(embed)
        return hidden, cell

# Creating decoder    
class Decoder(tf.keras.Model):
    def __init__(self, output_size, embed_size, hidden_size):
        super(Decoder, self).__init__()
        self.embedding = Embedding(output_size, embed_size)
        self.lstm = LSTM(hidden_size, return_sequences=True, return_state=True)
        self.dense = Dense(output_size)

    def call(self, data, hidden, cell):
        embed = self.embedding(data)
        lstm_out, hc, fc = self.lstm(embed, initial_state=[hidden, cell])
        output = self.dense(lstm_out)

        return output, hc, fc

In [12]:
# Creating an sequence to sequennce class using encoder and decoder

class Seq2seq(tf.keras.Model):
    def __init__(self, encoder, decoder):
        super(Seq2seq, self).__init__()
        self.encoder = encoder
        self.decoder = decoder

    def call(self, inputs, teacher_forcing_ratio = 1.0):
        src_data, targ_data = inputs
        targ_len = targ_data.shape[1]

        # Encoder

        hidden, cell = self.encoder(src_data)

        output_lst = []

        inputs = targ_data[:, 0:1]

        for i in range(1, targ_len):
            output, hidden, cell = self.decoder(inputs, hidden, cell)
            output_lst.append(output)

            inputs= targ_data[:,i:i+1] if random.random()>= teacher_forcing_ratio else tf.argmax(output, axis=-1, output_type=tf.int32)
        return tf.concat(output_lst, axis=1)

In [13]:
# Create a training function

def train(model, src_data, targ_data, epochs=50):
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)    #optimizer
    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')    #loss

    def train_step(src, tgt):

        with tf.GradientTape() as gtape:
            output = model([src, tgt])
            targ_labels = tgt[:, 1:]
            # print(tf.shape(targ_labels)[1])
            output = output[:, :tf.shape(tgt)[1], : ]

            mask = tf.cast(targ_labels != tam_vocab['<PAD>'], tf.float32)

            # loss
            loss = loss_fn(targ_labels, output)
            loss*=mask
            total_loss = tf.reduce_sum(loss)
            tokens = tf.reduce_sum(mask)
            mean_loss = total_loss/(tokens+1e-8)

        gradients = gtape.gradient(mean_loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        return mean_loss            

    for epoch in range(epochs):

        loss = train_step(src_data, targ_data)

        if epoch%10 == 0:
            print(f'Epochs: {epoch}, Loss: {loss.numpy():.2f}')

    print("Training Completed")

In [14]:
input_size = len(eng_vocab)
hidden_size = 32
embed_size = 10
output_size= len(tam_vocab)

encoder = Encoder(input_size, embed_size, hidden_size)
decoder = Decoder(output_size, embed_size, hidden_size)
s2s = Seq2seq(encoder, decoder)

In [15]:
train(s2s, eng_seq, tam_seq, epochs=150)

Epochs: 0, Loss: 2.99
Epochs: 10, Loss: 2.42
Epochs: 20, Loss: 2.00
Epochs: 30, Loss: 1.67
Epochs: 40, Loss: 1.34
Epochs: 50, Loss: 1.02
Epochs: 60, Loss: 0.70
Epochs: 70, Loss: 0.41
Epochs: 80, Loss: 0.21
Epochs: 90, Loss: 0.09
Epochs: 100, Loss: 0.04
Epochs: 110, Loss: 0.03
Epochs: 120, Loss: 0.02
Epochs: 130, Loss: 0.01
Epochs: 140, Loss: 0.01
Training Completed


In [16]:
id_tam_vocab = {i:k for k,i in tam_vocab.items()}

In [17]:
def translation_pre_processing(sequence_data):

    src_data = sent2indices(sequence_data.lower(), eng_vocab)
    src_seq = pad_sequences([src_data], padding='post', value= eng_vocab['<PAD>'])

    return src_seq

def translation(input):

    seq_input = translation_pre_processing(input)
    dec_input = tf.constant([[tam_vocab['<SOS>']]], dtype=tf.int32)

    hidden, cell = encoder(seq_input)

    print('English to Tamil translation')
    print(f'{input} ->' , end=' ')
    for _ in range(10):

        output, hidden, cell = decoder(dec_input, hidden, cell)
        dec_input = tf.argmax(output, axis=-1)
        op = tf.argmax(output[0, -1], axis=-1, output_type=tf.int32).numpy()

        if op == tam_vocab['<EOS>']:
            break

        print(id_tam_vocab[op], end=' ')


In [26]:
translation('she is cooking a book')

English to Tamil translation
she is cooking a book -> அவள் புத்தகம் சமைக்கிறேன் 